<?php
class RecursosCons_en {
  public $RecursosCons=array (
		
	/* GERAIS */	
	"charset"=>"UTF-8",			
	"extensao"=>"_en",	
	"extensao_img"=>"_en",
	"extensao_bd"=>"_en",
	"pag_title"=>"3xpro",

	/*####TRANSLATE####*/
	/* FUN?ES */
	"manutencao"=>"Maintenance",
	"manutencao2"=>"Website is under maintenance",
	"manutencao3"=>"We promise to be brief",
	"manutencao4"=>"More information",
	"pag_404"=>"The page you are looking for does not exist",
	"pag2_404"=>"What you're looking for isn't here.",
	"voltar_site"=>"Back to the site",
	"mail_msg_cx"=>"Email",
	"mail_msg_1"=>"You must fill in an email.",
	"mail_msg_2"=>"You must fill in a valid email address.",
	"mail_msg_3"=>"Subscription successful.",
	"mail_msg_4"=>"The email has already been subscribed.",
	"mail_msg_5"=>"You have received an email to confirm your subscription.",
	"pesquisa_msg"=>"Search product",
	"erro"=>"Error",
	"ok"=>"OK",
	"fechar"=>"Close",
	"altera"=>"Change",
	"cancelar"=>"Cancel",
	"remover"=>"To remove",
	"cookies_txt "=>"We use own and third-party cookies to give you a better experience and service. <br> To learn which cookies we use and how to disable them, read the cookie policy.?By ignoring or closing this message, and unless you have cookies turned off, you are agreeing to its use on this device.",
	"cookies_ok"=>"Accept",
	"cookies_mais"=>"Know more",
	"news_tit"=>"Ivo Cutelarias Newsletter",
	"news_subtit"=>"If you don't want to miss out on any campaign, promotion and news, subscribe to our newsletter and find out first.",
	"news_subs"=>"Enter your email",
	"news_btn"=>"Subscribe",
	"seguranca"=>"security code",
	"mais_info"=>"More information",
	"saiba_mais"=>"Know more",
	"bread_tit"=>"See",
	"bread_tit_det"=>"Go back to",
	"ver_todos"=>"See all",
	"ver_todas"=>"View all",
	"ver_menos"=>"See less",
	"sem_produtos"=>"Available soon",
	"sem_produtos_pesq"=>"No products were found for your search.",
	"prods_relacionados"=>"Related products",
	"direitos"=>"Ivo Cutelarias ? 2020. All rights reserved.?Development <a href='https://webtech-evolution.com 'rel='nofollow' target='_blank'> Webtech-Evolution ? </a>",
	"direitos2"=>"Ivo Cutelarias ? 2020. All rights reserved. <br> Development <a href='http://netgocio.pt 'rel='nofollow' target='_blank'> Netg?io ? </a>",
	"selecione"=>"Select",
	"password_error"=>"Password must contain at least 6 characters and 1 uppercase and 1 number",
	"aceito_termos"=>"I declare that I understand and accept the <a href='privacy-politics' target='_blank'> Privacy Policy </a> of the website www.ivocutelarias.com",
	"aceito_termos_reg"=>"I declare that I understand and accept the <a href='privacy-politics' target='_blank'> Privacy Policy </a> and the <a href='terms-conditions' target='_blank'> Terms and Conditions </a> of the website www.ivocutelarias.com",
	"aceito_news"=>"I declare that I want to receive the newsletter from the website www.ivocutelarias.com",
	"linguas"=>"Select Language",
	"nao"=>"Not",
	"sim"=>"Yes",
	"anterior"=>"Previous",
	"seguinte"=>"Following",
	"confirmar"=>"Confirm",
	"form_erro"=>"There are fields to complete",
	"valor"=>"Value",
	"disponivel_breve"=>"Available soon",

	/* MENU */
	"home"=>"Home",
	"apoio"=>"Support",
	"carrinho_top"=>"Cart",
	"marca"=>"Brand",
	"noticias"=>"News",
	"academia"=>"academy ",
	"faqs"=>"Faq's",
	"contactos"=>"Contact us",
	"produtos"=>"Products",
	"ivo_world"=>"Ivo World",
	"novidades"=>"News",
	"promocoes"=>"Promotions",
	"seleciona_pais_idioma"=>"Select your country and language:",
	"seleciona_idioma"=>"Select your language:",
	"selecionar_idioma"=>"Select a language",

	"online_office"=>"Online Office",
	"selection_of_product" => "products",
	"relevance"=>"Relevance",
	"profissoes"=>"PROFESSIONS",
	// New Menu


	/* FOOTER */
	"compre_online"=>"Buy online",
	"info_legal"=>"Legal information",
	"login_registo"=>"Login / Registration",
	"perguntas_frequentes"=>"Common questions",
	"pais"=>"Parents",
	"lingua"=>"Language",
	"quer_distribuidor"=>"Want to be a distributor?",
	"catalogo"=>"Catalog",

	"my_account"=>"My Account",

	/* FOOTER STORE MENU */ 

	"promocode"=>"Promocode",
	"best_seller"=>"Best seller",
	"Marcas"=>"Marcas",


	/* MENU MOBILE */


	/* HOME */
	"ler_mais"=>"Read more",
	"tit_filtrar1"=>"Filter by country",
	"tit_filtrar2"=>"Filter by city",


	/* FAQ */
	"faqhead"=>"Online Office",
	"faqtext"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec nibh ut lacus bibendum ullamcorper nec ac orci. Aliquam non dapibus elit. Sed convallis erat nec tortor suscipit, ac sodales odio pellentesque. Fusce consequat a tortor pulvinar imperdiet.",

	"idade"=>"Idade",
	"peso_atual"=>"Peso atual",
	"altura"=>"Altura",


	/* CONTATOS */
	"tit_contactos"=>"Client support",
	"tit_contactos2"=>"Talk to us",
	"formulario_contacto_msg"=>"Your contact has been sent successfully! <br> We'll get back to you soon. <br> <br> Thanks.",
	"nome"=>"Name",
	"localidade"=>"Locality",
	"contacto"=>"Contact",
	"mail"=>"Email",
	"email_conf"=>"Confirm email",
	"cancelar_subscricao"=>"Unsubscribe from newsletter",
	"cancelar_subscricao_sucesso"=>"Subscription successfully canceled",
	"cancelar_subscricao_erro"=>"Email does not exist in our database",
	"cancelar_emails_diferentes"=>"Emails are not the same",
	"assunto"=>"Subject matter",
	"mensagem"=>"Message",
	"enviar"=>"Submit",
	"limpar"=>"To clean",
	"campos_obrigatorios"=>"Required fields",
	"car_mail_7"=>"Best regards,",
	"dados_contacto"=>"Contact Details",
	"confirmar_subs"=>"Confirm Newsletter Subscription",
	"confirmar_subs_txt"=>"To confirm our newsletter subscription and keep up with all the news click on the following link: <br> <br> <a href='#link#' target='_ blank' style= 'font-weight: bold;' > Click here to confirm </a>",
	"confirmar_subs_tit"=>"Newsletter Subscription",
	"confirmar_subs_subject"=>"Newsletter Subscription - www.ivocutelarias.com",
	"mapa_google_ver"=>"View in Google Maps",
	"preencha_captcha"=>"Validate the security option.",

	/* NOTIFICACOES */
	"aceita_encomendas"=>"I accept to receive automatic Order notifications by email",
	"aceita_newsletter"=>"I declare that I want to receive the newsletter from the website www.ivocutelarias.com",
	"ar_alt_notificacoes"=>"Notifications successfully changed.",
	"aceita_vales"=>"Would you like to receive automatic discount vouchers?",

	/* PESQ */
	"pesquisa_txt"=>"Press ENTER to search and X to close.",
	"pesquisa_sug"=>"Most searched",
	"pesq_noticias"=>"News",
	"pesq_categorias"=>"Categories",
	"pesq_produtos"=>"Products",
	"pesq_outros"=>"Other Results",
	"pesq_destaques"=>"Highlights",
	"pesq_ordenar"=>"Sort results",
	"pesq_filtrar"=>"Filter Results",
	"pesq_ver_todos"=>"View all results",
	"pesq_resultados"=>"Results found:",
	"pesq_carregar_mais"=>"See more results",

	/* OUTDATED */
	"outdated_tit"=>"Your browser is out of date!",
	"outdated_txt"=>"Refresh your browser for a better experience and viewing of this site.",
	"outdated_btn"=>"Update your browser now",

	/* anular subscri?o */
	"anular_subscricao"=>"Unsubscribe",
	"anular_msg"=>"To unsubscribe from our newsletters please fill in your email address. <br> You can subscribe again at any time.",
	"anular"=>"Cancel",
	"news_remove_sucesso"=>"You have been successfully unsubscribed.",
	"news_remove_erro"=>"Email does not exist in our database.",

	/* FOLLOW AND WISH */
	"add_favoritos"=>"ADD TO FAVORITES",
	"favoritos"=>"Favorites",
	"pesq_fav"=>"Search Favorites",
	"favoritos_total"=>"Total Favorite Ads:",
	"favoritos_login"=>"Log in <a href='login.php'> Login </a> or <a href='login.php?anchor=form_regista'> Sign Up </a> to save your favorites",
	"tem_login_erro"=>"To add to favorites you will need to login",
	"adicionar_favoritos"=>"Add to Favorites",
	"favorito_anuncio_txt"=>"Want to add this product to your favorites?",
	"favorito_anuncio_suc"=>"Product successfully added!",
	"favorito_anuncio_txt2"=>"Remove this product from favorites?",
	"favorito_anuncio_suc2"=>"Product successfully removed!",

	/* LOJA */
	"ver_produto"=>"View product",
	"filtrar"=>"Apply filters",
	"limpar_filtrar"=>"Clear Filters",
	"mostrar_filtros"=>"Filters",
	"anterior"=>"previous",
	"seguinte"=>"Following",
	"voltar_listagem"=>"back to products",
	"filtar_sel"=>"Filter",
	"filtros"=>"Filters",
	"fechar_filtros"=>"Close filters",
	"filtrar_por"=>"Filter by",
	"apoio_ao_cliente" => "Client support",
	"ordenar"=>"Order by",
	"mais_recente"=>"A - Z",
	"mais_antigo"=>"Z - A",
	"mais_barato"=>"? - ???",
	"mais_caro"=>"??? - ?",
	"promocao"=>"Promotion",
	"em_promocao"=>"On sale",
	"novidade"=>"NEW",
	"carregar_mais"=>"View more",
	"prods_interesse"=>"IT MAY ALSO INTEREST YOU",
	"prods_recomendados"=>"Recommended Products",
	"prods_relacionados"=>"You may also like",
	"partilhar"=>"Share",
	"cores"=>"Colors",
	"mais_cores"=>"+ colors",
	"ver_detalhe"=>"See detail",
	"descricao"=>"description",
	"lamina"=>"Blade",
	"cabo"=>"Cable",
	"tamanho"=>"Size",
	"saber_mais"=>"To know more",
	"personalizacao"=>"Customization",
	"personalizacao_resumo_carrinho" => "Personalization (value included)",
	"custo_personalizacao"=>"Customization cost",

	/* CARRINHO HELPERS */
	"carrinho"=>"Shopping cart",
	"solicitar_contacto"=>"Budget request",
	"ir_carrinho"=>"Go to shopping cart",
	"add_carrinho"=>"Add",
	"vista_rapida"=>"Quick view",
	"comprar"=>"Purchase",
	"artigo_adicionado_suc"=>"Product successfully added!",
	"car_remover_artigo"=>"Remove article",
	"car_remover_artigo_txt"=>"Are you sure you want to remove this item from cart?",
	"cesto_de_compras_vazio"=>"Your cart is empty.?You can start filling it with presents ...",
	"cesto_de_compras_voltar"=>"View products",
	"carrinho_login"=>"You must be logged in to continue",
	"stock_zero"=>"No stock available for selected size.",
	"qtd_unidades"=>"Units",
	"qtd_unidade"=>"unity",
	"qtd_cada"=>"(each)",
	"car_confimar"=>"Yes",
	"car_cancelar"=>"Back to cart",

	/* CARRINHO */
	"carrinho_passo1"=>"Order",
	"carrinho_passo2"=>"Data, Shipping and Payment",
	"carrinho_passo3"=>"Checkout",
	"carrinho_contacto"=>"Budget",
	"carrinho_contacto2"=>"Finish budget",
	"cart_prod"=>"Product",
	"cart_qtd"=>"Amount",
	"cart_price"=>"Price",
	"cart_delete"=>"To eliminate",
	"carrinho_btn_prev"=>"Continue shopping",
	"carrinho_btn_next"=>"Place the order",
	"sem_stock_disponivel"=>"Out of stock available.",
	"com_stock"=>"In stock",
	"sem_stock"=>"Out of stock",
	"stock_actualizado"=>"The quantity indicated exceeds the product stock.?The quantity in cart has been adjusted to the stock available.",
	"insira_quantidade"=>"Enter quantity",
	"artigo_inserir_1"=>"Product successfully inserted.",
	"selecione"=>"Select",
	"carrinho_voltar"=>"Back to Online Store",
	"car_total"=>"Total",
	"activar_saldo_1"=>"Payment with the active Available Balance.",
	"activar_saldo_2"=>"Payment with Available Balance inactive.",
	"utilizar_saldo"=>"Use Available Balance",
	"desconto_unit"=>"Discount",
	"pontos_acumular"=>"You will earn ### points",
	"saldo_acumular"=>"Will accumulate ### in balance",
	"iva_incluido"=>"VAT included",
	"cheque_prenda_2"=>"Gift Check",
	"carrinho_erro1"=>"Payment and / or shipping method not selected!",
	"carrinho_erro2"=>"Invalid payment and / or shipping method for selected options!",
	"cart_semlogin_tit"=>"Complete purchase",
	"cart_semlogin_txt"=>"You are not logged in. <br> Do you want to login / register or would like to complete the purchase without login?",
	"cart_semlogin_btn1"=>"Register / Login",
	"cart_semlogin_btn2"=>"Finish without registration",
	"finalizar_encomenda"=>"Checkout",

	/* COMPRAR */
	"dados_faturacao"=>"Data billing",
	"dados_envio"=>"Shipping Data",
	"obs_encomenda"=>"Remarks on Order",
	"comprar_pagamento"=>"Payment method",
	"comprar_entrega"=>"Shipping Method",
	"comprar_observacoes"=>"Comments",
	"comprar_nome"=>"Name",
	"comprar_email"=>"Email",
	"comprar_contacto"=>"Contact",
	"comprar_nif"=>"Contributor",
	"comprar_pais"=>"Country Shipping",
	"comprar_sel_pais"=>"You must select a Country",
	"comprar_sel_pais2"=>"Select a country",
	"comprar_morada_fat"=>"Billing Address",
	"comprar_postal"=>"Cod.?Postcard",
	"comprar_localidade"=>"Locality",
	"comprar_portes_gratis"=>"Free Shipping",
	"comprar_resumo"=>"Order Summary",
	"comprar_saldo"=>"Balance available",
	"comprar_guardar"=>"Save",
	"comprar_acresce"=>"In addition",
	"comprar_seguinte"=>"Checkout:",
	"comprar_voltar"=>"Back to previous step",
	"comprar_edit"=>"To edit",
	"comprar_preencher"=>"There are fields to complete",
	"comprar_mesmos_dados"=>"I want to use this information for shipping data",
	"erro_nome_envio"=>"Please fill in name on shipping details",
	"erro_morada_envio"=>"You must fill in the address in the shipping data.",
	"erro_cod_postal_envio"=>"You must fill in the zip code in the shipping details",
	"erro_localidade_envio"=>"You must fill in location on shipping details",
	"erro_pais_envio"=>"You must fill in the country in the shipping details.",
	"erro_contacto_envio"=>"Please fill in contact details",
	"erro_nome_fatura"=>"Please fill in name in billing data",
	"erro_morada_fatura"=>"You must fill in the address in the billing data.",
	"erro_cod_postal_fatura"=>"You must fill in the zip code in your billing data",
	"erro_localidade_fatura"=>"You must fill in the location in your billing data",
	"erro_email_fatura"=>"Please fill in email in billing data",
	"erro_nif_fatura"=>"Must fill in taxpayer billing data",
	"erro_pais_fatura"=>"Please fill in country in billing data",
	"erro_envio"=>"You must select a shipping method",
	"erro_pagamento"=>"Select a payment method",
	"pais"=>"Country",
	"morada"=>"Address",

	/* COMPRAR 2 */
	"sua_encomenda"=>"Your Order",
	"portes_de_pagamento"=>"Payments",
	"portes_de_envio"=>"Shipping",

	/* COMPRAR 4 */
	"car_quantidade2"=>"Qty",
	"car_preco_unit"=>"Price together",
	"car_sub_total"=>"Subtotal",
	"iva"=>"VAT",
	"car_artigos"=>"Designation",
	"morada_facturacao"=>"Billing Address",
	"morada_envio"=>"Shipping Address",
	"pais_envio"=>"Country Shipping",
	"confirmar_encomenda"=>"confirm order",
	"comprar_msg_sucesso"=>"Your order has been completed. <br> Please pay with the details below.",
	"comprar_msg_sucesso2"=>"You will be contacted shortly for our services.",
	"contacto_msg_sucesso"=>"Your request has been successfully completed. <br> You will be contacted shortly by our services.",
	"car_encomenda_n"=>"Order #",
	"car_imprimir"=>"Print order data",
	"encomenda_num"=>"Order No.",
	"os_seus_dados"=>"PERSONAL DATA",
	"detalhe_da_encomenda"=>"ORDER DETAIL",
	"fazer_compra"=>"Return to store to continue shopping",
	"fazer_compra2"=>"Back to the store",
	"multibanco1"=>"Payment data:",
	"multibanco2"=>"ATM or Homebanking Payment",
	"multibanco3"=>"The receipt issued by the automated teller machine proves payment.?Keep it up.",
	"carr_pag_paypal"=>"Make PAYPAL Payment for Order",
	"car_comprar_paypal"=>"Make <strong> here </strong> your payment ?",
	"car_comprar_paypal_suc"=>"Payment made successfully. <br> Thank you.",
	"comprar4_entidade"=>"Entity",
	"comprar4_referencia"=>"Reference",
	"comprar4_montante"=>"Amount",
	"comprar4_obrigado"=>"Thank you for your preference!",
	"car_comprar_easypay"=>"Make <strong> here </strong> your payment ?",
	"info_pagamento"=>"Payment Information",
	"encomenda_paga"=>"Payment made successfully",

	/* EMAIL COMPRAR 4 */
	"car_resumo_enc"=>"Order Summary",
	"car_num_enc"=>"Order",
	"car_data_enc"=>"Date",
	"car_nome"=>"Name",
	"car_telefone"=>"telephone",
	"car_email"=>"Email",
	"car_nif"=>"Contributor",
	"car_morada_fact"=>"billing address",
	"car_morada_env"=>"Shipping Address",
	"car_pais"=>"Shipping Country",
	"car_pagamento"=>"Payment",
	"car_envio"=>"Send",
	"car_obs"=>"Comments",
	"car_mail_5"=>"Selected Products",
	"car_mail_subtotal"=>"Sub Total",
	"comprar4_texto"=>"This message will be sent automatically, if you have already paid, please ignore this email.",
	"car_mail_cliente"=>"Client Area",
	"car_mail_maisinfo"=>"If you have any questions <strong> contact us </strong>",
	"info_pagamento"=>"Payment Information",

	/* PORTES GRATIS */
	"por_mais"=>"There are only",
	"por_mais_2"=>"to enjoy Free Shipping on",
	"label_portes2"=>"Free shipping for",
	"portes"=>"free shipping",

	/* CONSOLA */
	"novo_contacto_tit"=>"Your contact has been registered - www.ivocutelarias.com",
	"novo_contacto_txt"=>"Hon.?Mr.?<strong>#nome#</strong>, <br> <br> Your request is being processed by our services. <br> <br> Thanks for your preference!",
	"nova_encomenda_tit"=>"Your order has been registered",
	"nova_encomenda_txt"=>"Hon.?Mr.?<strong>#nome#</strong>, <br> <br> Your order is being processed by our services.?You can check the order status on our website <a class='intro'href='http://www.ivocutelarias.com//area-reservada.php'> click here </a>. <br> <br> Thank you for your preference!",
	"encomenda_proc_tit"=>"Your order is currently being processed - www.ivocutelarias.com",
	"encomenda_proc_txt"=>"Hon.?Mr.?<strong>#nome#</strong>, <br> <br> Your order is currently being processed. <br> <br> Thanks for your preference!",
	"encomenda_env_tit"=>"Your order has been shipped - www.ivocutelarias.com",
	"encomenda_env_txt"=>"Hon.?Mr.?<strong>#nome#</strong>, <br> <br> Your order has been shipped. <br> <br> Thanks for your preference!",
	"encomenda_canc_tit"=>"Your order has been canceled - www.ivocutelarias.com",
	"encomenda_canc_txt"=>"Hon.?Mr.?<strong>#nome#</strong>, <br> <br> Your order has been canceled. <br> <br> Thanks for your preference!",
	"seguir_envio"=>"Follow Submission",
	"seguir_envio_cod"=>"Code",
	"seguir_envio_clique"=>"click here",

	/*PROMO?ES*/
	"promocao_datas"=>"Valid promotion from <span>#datai# to #dataf#.</span>",
	"promocao_titulo"=>"Promotion Conditions",
	"promocao_link"=>"See Conditions",
	"promocoes_ver_mais"=>"More information",

	/* TICKETS */
	"ar_meus_tickets"=>"Help/Suggestions",
	"sem_tickets"=>"You have not yet submitted a help request. <br> Fill out the form to contact support.",
	"sem_tickets2"=>"New request:",
	"formulario_tickets_msg"=>"Your request has been submitted successfully! <br> We'll get back to you soon. <br> <br> Thanks.",
	"tck"=>"New request - www.ivocutelarias.com",
	"tck_nome"=>"Client name",
	"tck_data"=>"Date",
	"tck_Ticket"=>"Help/Suggestions",
	"tck_estado"=>"state",
	"tck_email"=>"Customer Email",
	"tck_assunto"=>"Subject matter",
	"tck_descricao"=>"description",
	"tck_mensagens"=>"View posts",
	"tck_resposta"=>"answer",
	"tck_resposta_2"=>"Please consult your personal area for the request response.",
	"tck_resposta_3"=>"Response to the ticket at www.ivocutelarias.com",
	"tck_responder"=>"Fill in the form to reply to the request.",
	"tck_remetente"=>"Sender",
	"aberto"=>"Open",
	"concluido"=>"completed",
	"novo_ticket"=>"Create new order",
	"nova_resposta"=>"New answer",
	"resposta_sucesso"=>"Your reply was sent successfully! <br> We'll get back to you soon. <br> <br> Thanks.",
	"upload"=>"Upload",
	"anexos"=>"Attachments",
	"tickets_ficheiros"=>"Shared Files",
	"selecione_ficheiros"=>"Select files",
	"tck_tipo"=>"Type",
	"tickets_abertos"=>"Open request",

	/* LOGIN / REGISTO */
	"login"=>"Login",
	"login_tit"=>"Already registered??Login",
	"registo_tit"=>"Create a new record",
	"login_lembrar"=>"Save my access data",
	"login_redes"=>"Or login with",
	"reg_redes"=>"You can also create your registration with",
	"password"=>"Password",
	"entrar"=>"Log in",
	"criar_registo"=>"Create record",
	"primeiro_nome"=>"First name",
	"ultimo_nome"=>"Last name",
	"profissional"=>"Companies",
	"entidades"=>"Entities",
	"particular"=>"Final costumer",
	"validar_registo_btn"=>"Validate Registration",
	"ar_mail_reg"=>"Welcome |?Ivo Cutlery",
	"ar_mail_reg_novo_tit"=>"Registration Data",
	"reg_mail_txt"=>"Welcome?Ivo Cutelarias, <br> <br> To validate your registration <a href=\"#link#\" style=\"font-weight: 600; font-size: 13px; text-decoration: underline;\"> click here </a>. <br> <br> Thanks so much for your preference.",
	"reg_mail_front"=>"Welcome, your registration has been successfully completed.",
	"recupera_password"=>"Forgot your password?",
	"recuperar_password"=>"Password Recovery",
	"recuperar_password_txt"=>"Click the link below to change your password.",
	"recupera_password_clique"=>"click here",
	"recupera_password_link"=>"to change your password",
	"recuperar_email_sucesso"=>"The email has been sent.",
	"recuperar_msg_sucesso"=>"Password changed successfully",
	"recuperar_msg_erro"=>"The link is not valid.",
	"recuperar_email_erro"=>"There was an error sending the email.?Please try again later",
	"reg_aviso_prof"=>"Registration successfully created! <br> <br> Your registration must be validated by the administration before you can access your account.",
	"area_erro_1"=>"You must enter a username.",
	"area_erro_11"=>"You must enter a valid email address.",
	"area_erro_12"=>"You must enter a password.",
	"area_erro_2"=>"Email and / or password do not match.?Please confirm the data.",
	"area_erro"=>"No permission to access reserved area.",
	"validar_conta"=>"Verify Account",
	"validar_conta_txt"=>"Your account has not been validated yet.?Do you want to resend the verification email?",
	"validar_conta_txt2"=>"The email has been sent.?If you do not receive the email, check your spam box!",
	"validar_conta_txt3"=>"Validate your account via the link",
	"entidades"=>"Entities",
	"criar_registo_msg_sucesso"=>"An email has been sent to validate your account. <br> If you do not receive the email, check the spam box. <br> Thanks.",
	"dados_acesso"=>"Access data",
	"reg_mail_txt2"=>"Welcome?<a href=\"https://www.ivocutelarias.com//\"> Ivo Cutelarias </a>, <br> <br> Your registration will be validated by the online store management. <br> You will receive a email as soon as your account is validated. <br> <br> Thanks so much for your preference.",
	"reg_mail_txt_admin"=>"To validate this customer\"s registration <a href=\"#link#\" style=\"font-weight: 600; font-size: 13px; text-decoration: underline;\"> click here </a>",
	"registo_sucesso"=>"Registration successfully created!",
	"validar_registo"=>"Your registration has been successfully validated!",
	"validar_registo_erro"=>"Your registration has not yet been validated by the administration!",
	"validar_registo_tit"=>"Registration successfully validated",
	"area_mail_registado"=>"Email is already registered.",
	"area_nif_registado"=>"The taxpayer number is already registered.",
	"qual"=>"Indicate which",
	"selecione_market"=>"You must select country <strong>#pais#</strong> in order to log in",

	/* AREA PESSOAL */
	"bem_vindo"=>"Welcome to",
	"ar_ver_detalhe"=>"View Detail",
	"sem_encomendas"=>"You have not placed any orders yet",
	"area_reservada"=>"Personal Area",
	"area_entrada"=>"Input",
	"minhas_encomendas"=>"Orders",
	"meus_favoritos"=>"Favorites",
	"meus_dados"=>"Personal data",
	"minhas_moradas"=>"Addresses",
	"meus_amigos"=>"Invite friends",
	"meus_tickets"=>"Talk to us",
	"minhas_notificacoes"=>"Notifications",
	"logout"=>"Logout",
	"msg_logout"=>"Do you want to sign out of your account?",
	"sem_registos"=>"There are no results to display.",
	"sem_favoritos"=>"You haven't added any products to favorites yet.",
	"sem_seguir_preco"=>"You are not following product prices yet.",
	"alterar_password"=>"Change Password",
	"eliminar_conta"=>"Delete Account",
	"eliminar_conta_desc"=>"Reason",
	"eliminar_conta_msg"=>"By deleting the account you will lose the ability to make purchases and other benefits at www.ivocutelarias.com. <br> Are you sure you do not want to reconsider this decision??Tell us the reason for the cancellation.",
	"novo_registo"=>"New registration on the site - www.ivocutelarias.com",
	"preencha_dados"=>"Fill in your personal details to continue.",
	"ar_email"=>"Email",
	"ar_email_conf"=>"Confirm email",
	"ar_password"=>"Password",
	"ar_password_conf"=>"Confirm Password",
	"ar_contribuinte"=>"Contributor",
	"ar_tipo"=>"Type",
	"ar_produto"=>"Product",
	"ar_empresa"=>"Company Name",
	"ar_responsavel"=>"Full guardian name",
	"ar_morada"=>"address",
	"ar_morada2"=>"Select another Address",
	"ar_morada3"=>"You haven't added any other contacts yet.",
	"ar_cpostal"=>"Postal Code",
	"ar_cpostal2"=>"(0000-000)",
	"ar_localidade"=>"Locality",
	"ar_pais"=>"Parents",
	"ar_selecione_pais"=>"Select a country",
	"ar_pessoa_contacto"=>"Contact person",
	"ar_cargo"=>"Office",
	"ar_telefone"=>"telephone",
	"ar_fax"=>"Fax",
	"ar_telemovel"=>"Mobile phone",
	"ar_nome"=>"Full name",
	"ar_referer"=>"Invited by",
	"ar_particular"=>"Private",
	"ar_profissional"=>"Professional",
	"ar_data_nasc"=>"Date of birth",
	"ar_data_nasc2"=>"(yyyy-mm-dd)",
	"meu_saldo"=>"My balance",
	"saldo_disponivel"=>"Balance available",
	"dados_pessoais"=>"Personal data",
	"ar_alt_dados"=>"Your registration details have been successfully changed.",
	"acumule_saldo"=>"Collect #valor# in your balance",
	"codigo_validado"=>"Code has been validated successfully.",
	"codigo_nao_validado"=>"Code entered is not valid.",
	"validar_cheque"=>"validate gift check",
	"inserir_codigo"=>"Enter the Gift Certificate code",
	"validar"=>"validate",
	"pontos_disponiveis"=>"Available Points",
	"trocar_pontos"=>"Swap Points",
	"trocar_pontos_sucesso"=>"Points redeemed successfully.",
	"cheque_prenda_num"=>"Gift Certificate N .:",
	"trocar_pontos_em_saldo"=>"Convert points to balance",
	"pontos_converter_1"=>"You can convert",
	"pontos_converter_2"=>"pts on",
	"pontos_converter_erro"=>"You have no points available to convert to balance.",
	"troca_pontos_tit"=>"Points Exchange",
	"enc_abertas"=>"Open Orders",
	"filtrar_enc"=>"Filter orders",
	"pesq_enc"=>"Search orders",
	"rep_encomenda"=>"Repeat",
	"rep_encomenda_tit"=>"Repeat Order",
	"rep_encomenda_txt"=>"Do you want to repeat order <strong> ##num# </strong>? <br> <strong> Note: </strong> Only products currently available will be added to your cart.",
	"ar_actividade"=>"Activity",
	"outro"=>"Other",
	"ar_morada_principal"=>"Main Address",
	"ar_outras_moradas"=>"Other Addresses",
	"adicionar_morada"=>"Add new address",
	"ar_inserir"=>"Insert",
	"ar_editar"=>"Edit",
	"ar_remover"=>"Remove",
	"distrito"=>"District",
	"ar_ins_morada"=>"Address added successfully.",
	"ar_rem_morada"=>"Address successfully deleted.",
	"ar_remover_morada_tit"=>"Delete Address",
	"ar_remover_morada"=>"Are you sure you want to delete this address?",
	"accoes"=>"Actions",

	/* NOTIFICA?ES */
	"notificacao_tit"=>"Order Notification",
	"notificacao_paypal"=>"Pay here by Paypal",
	"notificacao_pag"=>"Payment data",

	/* C?IGOS PROMOCIONAIS	 */
	"codigo_promocional_txt"=>"If you have any promo codes, enter the code here",
	"codigo_promocional_aplicar"=>"Validate",
	"codigo_promocional_mensagem_1"=>"Enter a promo code.",
	"codigo_promocional_mensagem_2"=>"Promo code is not valid.",
	"codigo_promocional_mensagem_3"=>"Order total does not allow you to use this promotional code.",
	"codigo_promocional_mensagem_4"=>"Valid promotional code.",
	"codigo_promocional_mensagem_5"=>"Error entering promo code.",
	"codigo_promocional_mensagem_6"=>"You have already used this code as many times as possible.",
	"codigo_promocional_mensagem_7"=>"This code can only be used on non-discounted products.",
	"codigo_promocional_mensagem_8"=>"This code cannot be used by the Customer Group to which it belongs.",
	"codigo_promocional_mensagem_9"=>"This code is not valid for your registration.",
	"codigo_promocional_mensagem_10"=>"This code is not valid for the selected products.",
	"codigo_promocional"=>"Promotional code",
	"codigo_promo_remover"=>"Remove code",
	"codigo_promo_remover_txt"=>"Are you sure you do not want to use the code?",
	"codigo_promocional_inserir"=>"Use promo code",
	"a_equipa"=>"The <span style = 'font-weight: bold'> Ivo Cutelarias team </span>",
	"oferta_link"=>"To enjoy the promotion click on the following link:",
	"oferta_ate"=>"You can take advantage of this offer up to #cdata#.",
		
	/* QUERO SER DISTRIBUIDOR */
	"quero_ser_distribuidor"=>"I want to be a Distributor",
	"contacte-nos"=>"Contact us",

	"product_details"=>"Descri?o do produto",
	//"product_spec"=>"ESPECIFICA?ES",
	"product_reviews"=>"Coment?ios",

	"product_video"=>"V?eos",
	"product_informacao"=>"Informa?o T?nica",

		/*####TRANSLATE####*/		

		// Filter Order

	"order_em_populares"=>"More popular",
	"order_em_promocao"=>"On Sale",
	"order_em_novidades"=>"News",
	"order_em_destaque"=>"Highlighted",

	"price_label"=>"Pre?",
	"euro_label"=>"?",

	"last_viewed_head"=>"Last viewed",
	"natura_online"=> "3xpro",

	"footer_logo_sub_head"=>"Do you represent a company / institution? Visit us at",
	
	"news_title"=>"Visit our facilities",

	"subscribe_top_title"=>"Fique a par das novidades",
	"news_title"=>"Visite as nossas instala?es",
	"news_subs"=>"O seu email",
	"news_btn"=>"Subscrever",

	"view_more_button"=> "View More",

	);
}
?>